# Generated by Django 5.0.4 on 2024-05-10 00:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ourvalues_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.URLField(blank=True, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='upload photo', max_length=255, null=True, verbose_name='image')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='our_mission_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='upload image for Mission section', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='our_story_image1',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='upload first for Story section', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='our_story_image2',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='upload second for Story section', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ourvalues',
            name='value_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='upload image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload site logo', max_length=255, null=True, verbose_name='image'),
        ),
    ]
