# Generated by Django 5.0.4 on 2024-05-10 14:56

import cloudinary.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_team_about_our_mission_image_about_our_story_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='upload logo of trusted-by companies/businesses', max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Trusted By Businesses',
            },
        ),
        migrations.AlterField(
            model_name='ourvalues',
            name='value_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
