# Generated by Django 5.0.4 on 2024-05-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_importantpages_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='Enter the google map iframe embed src link', max_length=1000, null=True),
        ),
    ]
