# Generated by Django 4.2.13 on 2024-05-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('home', '0010_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='privacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
