# Generated by Django 4.2.13 on 2024-05-16 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('home', '0012_sitelogo_sign_in_image_sitelogo_sign_up_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_note', models.CharField(blank=True, help_text='Free shipping on orders $100+', max_length=500, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
