# Generated by Django 4.2.13 on 2024-07-08 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_bag', to='shop.orderbag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product', to='shop.productpage')),
            ],
        ),
        migrations.AddField(
            model_name='orderbag',
            name='order_items',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.productpage'),
        ),
        migrations.AddField(
            model_name='orderbag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('full_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_cart', to='shop.cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.orderbag')),
            ],
        ),
    ]
