# Generated by Django 4.2.13 on 2024-05-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryIndexPage',
        ),
    ]
