# Generated by Django 5.0.4 on 2024-05-06 15:58

import datetime
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, help_text='Enter a product category', max_length=500, null=True, unique=True)),
                ('category_description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='product_category',
        ),
        migrations.AlterField(
            model_name='productpage',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='shop.category'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productpage')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
    ]
