# Generated by Django 5.0.4 on 2024-05-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_remove_productpage_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
