# Generated by Django 5.0.4 on 2024-05-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_phone_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='B3cPugTsvXB', max_length=500),
        ),
        migrations.AddField(
            model_name='productpage',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
