# Generated by Django 5.0.4 on 2024-05-13 21:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productpage_sku_productpage_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='additional_information',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='PouAE4c7AZV', max_length=500),
        ),
    ]
