# Generated by Django 5.0.4 on 2024-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productpage_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='vOvnPXYoq1Z', max_length=500),
        ),
    ]
