# Generated by Django 5.0.4 on 2024-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productpage_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='uNzmwEWk26I', max_length=500),
        ),
    ]
