# Generated by Django 5.0.4 on 2024-05-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productpage_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='SKU',
        ),
    ]
