# Generated by Django 5.0.4 on 2024-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_productpage_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='mzBw4Pymnv4', max_length=500),
        ),
    ]
