# Generated by Django 5.0.4 on 2024-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productpage_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='SStISKD0g39', max_length=500),
        ),
    ]
