# Generated by Django 5.0.4 on 2024-05-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_productpage_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='KNA3IioHzdB', max_length=500),
        ),
    ]
