# Generated by Django 5.0.4 on 2024-05-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_productpage_quantity_alter_productpage_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='eVoKFiPoJAn', max_length=500),
        ),
    ]
