# Generated by Django 4.2.13 on 2024-05-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productpage_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='SKU',
            field=models.CharField(default='VPj2CDvfB95', max_length=500),
        ),
    ]
