# Generated by Django 4.2.13 on 2024-05-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_productpage_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='SKU',
        ),
    ]
